-- =============================================================
-- Fix: Add missing columns to existing savings_products table
-- Run this in Supabase SQL Editor if migration 0033 was not applied
-- =============================================================

ALTER TABLE savings_products
  ADD COLUMN IF NOT EXISTS name_nepali varchar(100),
  ADD COLUMN IF NOT EXISTS product_category text,
  ADD COLUMN IF NOT EXISTS is_system boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_by uuid,
  ADD COLUMN IF NOT EXISTS updated_by uuid,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS interest_posting_frequency text NOT NULL DEFAULT 'Monthly',
  ADD COLUMN IF NOT EXISTS interest_calculation_method text NOT NULL DEFAULT 'min_monthly_balance',
  ADD COLUMN IF NOT EXISTS interest_effective_date text,
  ADD COLUMN IF NOT EXISTS min_deposit numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_deposit numeric(15,2),
  ADD COLUMN IF NOT EXISTS max_balance numeric(15,2),
  ADD COLUMN IF NOT EXISTS tenure_months integer,
  ADD COLUMN IF NOT EXISTS penalty_rate numeric(6,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eligible_member_type_ids jsonb NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS min_age integer,
  ADD COLUMN IF NOT EXISTS max_age integer,
  ADD COLUMN IF NOT EXISTS requires_kyc_verified boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS requires_nominee boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS requires_photo boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS requires_signature boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS requires_documents boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS opening_deposit_required boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS account_no_prefix varchar(10) NOT NULL DEFAULT 'SAV',
  ADD COLUMN IF NOT EXISTS deposit_mode_cash boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS deposit_mode_bank boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS deposit_mode_transfer boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS deposit_mode_agent boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS daily_deposit_limit numeric(15,2),
  ADD COLUMN IF NOT EXISTS monthly_deposit_limit numeric(15,2),
  ADD COLUMN IF NOT EXISTS backdate_deposit_allowed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS deposit_requires_approval boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS withdrawal_mode_cash boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS withdrawal_mode_transfer boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS min_withdrawal numeric(15,2),
  ADD COLUMN IF NOT EXISTS max_withdrawal numeric(15,2),
  ADD COLUMN IF NOT EXISTS daily_withdrawal_limit numeric(15,2),
  ADD COLUMN IF NOT EXISTS monthly_withdrawal_limit numeric(15,2),
  ADD COLUMN IF NOT EXISTS minimum_balance_after_withdrawal numeric(15,2),
  ADD COLUMN IF NOT EXISTS withdrawal_requires_approval boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS min_balance_grace_days integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_balance_penalty_percent numeric(6,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_balance_penalty_amount numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_balance_penalty_frequency text NOT NULL DEFAULT 'Monthly',
  ADD COLUMN IF NOT EXISTS min_balance_waiver_allowed boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS inactive_after_months integer NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS dormant_after_months integer NOT NULL DEFAULT 6,
  ADD COLUMN IF NOT EXISTS notify_before_dormancy_days integer NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS reactivation_required boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS reactivation_approval_required boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS closure_allowed boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS minimum_balance_before_closure numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS closure_requires_approval boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS closure_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS opening_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS monthly_maintenance_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawal_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cheque_book_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cheque_leaf_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stop_payment_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cheque_return_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passbook_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS statement_fee numeric(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cheque_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS cheque_default_leaves integer NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS cheque_max_books integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS cheque_validity_days integer NOT NULL DEFAULT 90,
  ADD COLUMN IF NOT EXISTS gl_liability_account_id uuid,
  ADD COLUMN IF NOT EXISTS gl_interest_expense_account_id uuid,
  ADD COLUMN IF NOT EXISTS gl_interest_payable_account_id uuid,
  ADD COLUMN IF NOT EXISTS gl_fee_income_account_id uuid,
  ADD COLUMN IF NOT EXISTS gl_penalty_income_account_id uuid,
  ADD COLUMN IF NOT EXISTS gl_cheque_income_account_id uuid;

-- Also create savings_interest_rates and savings_cheque_books if they don't exist
CREATE TABLE IF NOT EXISTS savings_interest_rates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  savings_product_id uuid NOT NULL REFERENCES savings_products(id) ON DELETE CASCADE,
  rate numeric(6,4) NOT NULL DEFAULT 0,
  effective_from_bs text NOT NULL,
  effective_to_bs text,
  created_by uuid,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS savings_cheque_books (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  savings_account_id uuid NOT NULL REFERENCES savings_accounts(id) ON DELETE CASCADE,
  book_no text NOT NULL,
  issued_date_bs text NOT NULL,
  total_leaves integer NOT NULL DEFAULT 25,
  used_leaves integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Active',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

SELECT 'Migration complete: savings_products columns added.' AS result;
